# Generated by Django 2.2 on 2020-05-24 10:34

import apps.ocr.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='文件名称')),
                ('image', models.ImageField(upload_to=apps.ocr.models.upload_image_path, verbose_name='上传图像')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
            },
        ),
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='识别字母')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ImageFile', verbose_name='图片文件')),
            ],
            options={
                'verbose_name': '识别结果',
                'verbose_name_plural': '识别结果',
            },
        ),
    ]
